@base_address = http://localhost:8080

### Создать новый отель 
POST {{base_address}}/addNewHotel
Content-Type: application/json

{
  "id": "guid-1-hotel",
  "name": "CatRaHotel",
  "address": "г. Котязнь, ул. Мемная. д 7",
  "hotelStarRating": 4.2
}

### Обновить рейтинг отеля 
POST {{base_address}}/updateHotelStarRating/guid-1-hotel
Content-Type: application/json

{
  "hotelStarRating": 4.6
}

### Добавление новой комнаты
POST {{base_address}}/addNewRoom/guid-1-hotel
Content-Type: application/json

{
  "id": "guid-1-room",
  "numberRoom": "101D"
}

### Добавление новой комнаты
POST {{base_address}}/addNewRoom/guid-1-hotel
Content-Type: application/json

{
  "id": "guid-2-room",
  "numberRoom": "201A"
}

### Получить список всех отелей
GET {{base_address}}/hotels

### Получить список всех комнат
GET {{base_address}}/rooms

